### ISSUE TITLE
des news 

### ISSUE THREAD

**Issue by PierreLAURENT94** [lucas7731/Mw03#1]
bossez mr

**Comment by lucas7731** [comment]
je le fais Mr Le Vice Président du Sénat 
Mr Pierre Laurent

**Comment by PierreLAURENT94** [comment]
FAUX vous ne faite rien depuis 20 ans !

**Comment by lucas7731** [comment]
comment vous le savez car je ne vous connaissez pas il ya 20 ans

**Comment by PierreLAURENT94** [comment]
je suis ton père

**Comment by lucas7731** [comment]
OH NON

**Comment by PierreLAURENT94** [comment]
avorton

**Comment by lucas7731** [comment]
bon la plaisanterie a assez durer viens m aider sur mon programme

**Comment by PierreLAURENT94** [comment]
[https://github.com/PierreLAURENT94/MS5](url) GO
